sudo: false
language: go
go:
  - 1.16.x

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - export CGO_ENABLED="0"
  - go env

script:
  - cd basics
  - env GO111MODULE=on go test ./...
  - cd ../data-node
  - env GO111MODULE=on go test ./...
